name: smart_expense_tracker
description: A comprehensive expense tracking app for students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Charts and Data Visualization
  fl_chart: ^0.65.0

  # Date and Number Formatting
  intl: ^0.19.0

  # Database
  hive: ^2.1.0 # Or the latest stable version
  hive_flutter: ^1.1.0
  path: ^1.8.3
  # Local Notifications
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  # Shared Preferences for theme persistence
  shared_preferences: ^2.2.2

  # Firebase for authentication and storage
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.1 # Or the latest stable version
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  # Add assets folder if you have images
  # assets:
  #   - assets/images/